// Writes src/version.ts with the Git commit this build was produced from.
//
// The value has to be generated as source, not read from the environment at runtime: tsc bakes it
// into lib/ as a string literal, so a stale lib physically cannot report a fresh commit. Reading it
// from process.env would let an outdated deployment claim to be current, which defeats the detector.
//
// There is deliberately no fallback value. If the commit cannot be resolved the build fails, because
// a placeholder would be reported identically by every probe and the post-deploy check would pass
// without checking anything.
import { execSync } from 'node:child_process'
import { writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const target = join(here, '..', 'src', 'version.ts')

let sha
try {
  const git = (args) =>
    execSync(`git ${args}`, { cwd: here, stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim()
  const head = git('rev-parse --short HEAD')
  sha = git('status --porcelain') ? `${head}-dirty` : head
} catch (error) {
  console.error('[gen-version] Cannot resolve the Git commit. A build that cannot identify itself must not be deployed.')
  console.error(`[gen-version] ${error.message}`)
  process.exit(1)
}

// The value is interpolated into generated source, so keep it to the shape git can actually produce.
if (!/^[0-9a-f]{7,40}(-dirty)?$/.test(sha)) {
  console.error(`[gen-version] Refusing to emit an unexpected commit value: ${sha}`)
  process.exit(1)
}

writeFileSync(
  target,
  `// GENERATED by scripts/gen-version.mjs during \`npm run build\` - do not edit, do not commit.\n`
  + `export const BUILD_SHA = '${sha}'\n`,
  'utf8'
)

console.log(`[gen-version] BUILD_SHA=${sha}`)
